import type { Metadata } from "next";
import { Fredoka, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const fredokaSans = Fredoka({
    variable: "--font-fredoka-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${fredokaSans.className} ${geistSans.variable} ${geistMono.variable} antialiased bg-linear-to-bl from-[#f7d1bf] via-[#d6abe6] to-[#cfeffa]`}
            >
                {children}
            </body>
        </html>
    );
}
